import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.scss";
import Footer from "@/widget/layout/Footer/Footer";
import Header from "@/widget/layout/Header/Header";

const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Aiqonz Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={syne.className}>
      <body>
        <div className="layout">
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
